extern const GeoLayout rotate_final_geo[];
extern u8 rotate_final_ci4_nat_metal_ci4[];
extern u8 rotate_final_ci4_nat_metal_ci4_pal_rgba16[];
extern u8 rotate_final__0E018C10_ia8[];
extern Vtx rotate_final_Rotate_mesh_layer_1_vtx_0[227];
extern Gfx rotate_final_Rotate_mesh_layer_1_tri_0[];
extern Vtx rotate_final_Rotate_mesh_layer_5_vtx_0[32];
extern Gfx rotate_final_Rotate_mesh_layer_5_tri_0[];
extern Gfx mat_rotate_final_f3dlite_material_004[];
extern Gfx mat_revert_rotate_final_f3dlite_material_004[];
extern Gfx mat_rotate_final_Grate[];
extern Gfx mat_revert_rotate_final_Grate[];
extern Gfx rotate_final_Rotate_mesh_layer_1[];
extern Gfx rotate_final_Rotate_mesh_layer_5[];
extern Gfx rotate_final_material_revert_render_settings[];
