extern const GeoLayout final_boss_area_1_geo[];
extern const GeoLayout final_boss_area_1[];
extern const Collision final_boss_area_1_collision[];
extern const MacroObject final_boss_area_1_macro_objs[];
extern Lights1 final_boss_dl_f3dlite_material_001_lights;
extern Lights1 final_boss_dl_f3dlite_material_lights;
extern Lights1 final_boss_dl_f3dlite_material_003_lights;
extern u8 final_boss_dl_Material14_ci8[];
extern u8 final_boss_dl_Material14_ci8_pal_rgba16[];
extern u8 final_boss_dl_Material15_ci8[];
extern u8 final_boss_dl_Material15_ci8_pal_rgba16[];
extern Vtx final_boss_dl_Main_mesh_layer_1_vtx_0[72];
extern Gfx final_boss_dl_Main_mesh_layer_1_tri_0[];
extern Vtx final_boss_dl_Main_mesh_layer_1_vtx_1[72];
extern Gfx final_boss_dl_Main_mesh_layer_1_tri_1[];
extern Vtx final_boss_dl_Main_mesh_layer_1_vtx_2[50];
extern Gfx final_boss_dl_Main_mesh_layer_1_tri_2[];
extern Gfx mat_final_boss_dl_f3dlite_material_001[];
extern Gfx mat_revert_final_boss_dl_f3dlite_material_001[];
extern Gfx mat_final_boss_dl_f3dlite_material[];
extern Gfx mat_revert_final_boss_dl_f3dlite_material[];
extern Gfx mat_final_boss_dl_f3dlite_material_003[];
extern Gfx final_boss_dl_Main_mesh_layer_1[];
extern Gfx final_boss_dl_material_revert_render_settings[];
