#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/final_boss/leveldata.inc.c"

#include "levels/final_boss/DoorFloor1/collision.inc.c"
#include "levels/final_boss/DoorFloor1/model.inc.c"
#include "levels/final_boss/rotate_final/collision.inc.c"
#include "levels/final_boss/rotate_final/model.inc.c"
#include "levels/final_boss/cage_lip/collision.inc.c"
#include "levels/final_boss/cage_lip/model.inc.c"
#include "levels/final_boss/disappear_plat/model.inc.c"
#include "levels/final_boss/disappear_plat/collision.inc.c"
#include "levels/final_boss/final_slip/collision.inc.c"
#include "levels/final_boss/final_slip/model.inc.c"