extern const GeoLayout wall_jump_slip_geo[];
extern u8 wall_jump_slip_ci4_nat_metal_ci4[];
extern u8 wall_jump_slip_ci4_nat_metal_ci4_pal_rgba16[];
extern u8 wall_jump_slip__0E004810_i8[];
extern Vtx wall_jump_slip_Move_mesh_layer_1_vtx_0[12];
extern Gfx wall_jump_slip_Move_mesh_layer_1_tri_0[];
extern Vtx wall_jump_slip_Move_mesh_layer_1_vtx_1[30];
extern Gfx wall_jump_slip_Move_mesh_layer_1_tri_1[];
extern Gfx mat_wall_jump_slip_Floor[];
extern Gfx mat_revert_wall_jump_slip_Floor[];
extern Gfx mat_wall_jump_slip_Wall[];
extern Gfx mat_revert_wall_jump_slip_Wall[];
extern Gfx wall_jump_slip_Move_mesh_layer_1[];
extern Gfx wall_jump_slip_material_revert_render_settings[];
