extern const GeoLayout falling_stage_1_geo[];
extern u8 falling_stage_1__0E004810_i8[];
extern u8 falling_stage_1_ci4_nat_metal_ci4[];
extern u8 falling_stage_1_ci4_nat_metal_ci4_pal_rgba16[];
extern Vtx falling_stage_1_Fall_001_mesh_layer_1_vtx_0[73];
extern Gfx falling_stage_1_Fall_001_mesh_layer_1_tri_0[];
extern Vtx falling_stage_1_Fall_001_mesh_layer_1_vtx_1[18];
extern Gfx falling_stage_1_Fall_001_mesh_layer_1_tri_1[];
extern Gfx mat_falling_stage_1_Wall[];
extern Gfx mat_revert_falling_stage_1_Wall[];
extern Gfx mat_falling_stage_1_Floor[];
extern Gfx mat_revert_falling_stage_1_Floor[];
extern Gfx falling_stage_1_Fall_001_mesh_layer_1[];
extern Gfx falling_stage_1_material_revert_render_settings[];
