extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Lights1 pss_dl_f3dlite_material_001_lights;
extern Lights1 pss_dl_f3dlite_material_004_lights;
extern Lights1 pss_dl_f3dlite_material_003_lights;
extern Lights1 pss_dl_f3dlite_material_002_lights;
extern Lights1 pss_dl_f3dlite_material_lights;
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_2[4];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_3[4];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_4[8];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_4[];
extern Gfx mat_pss_dl_f3dlite_material_001[];
extern Gfx mat_pss_dl_f3dlite_material_004[];
extern Gfx mat_pss_dl_f3dlite_material_003[];
extern Gfx mat_pss_dl_f3dlite_material_002[];
extern Gfx mat_pss_dl_f3dlite_material[];
extern Gfx pss_dl_Cube_mesh_layer_1[];
extern Gfx pss_dl_material_revert_render_settings[];
