extern const GeoLayout troll_test_area_1_geo[];
extern const GeoLayout troll_test_area_1[];
extern const Collision troll_test_area_1_collision[];
extern const MacroObject troll_test_area_1_macro_objs[];
extern Lights1 troll_test_dl_Floor_001_lights;
extern Lights1 troll_test_dl_Wall_001_lights;
extern Lights1 troll_test_dl_Interaction_001_lights;
extern Lights1 troll_test_dl_Interaction_002_lights;
extern Lights1 troll_test_dl_Death_lights;
extern u8 troll_test_dl_tex1_128x128_b07ede22d4ecf1c8_14_ci8[];
extern u8 troll_test_dl_tex1_128x128_b07ede22d4ecf1c8_14_ci8_pal_rgba16[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_0[19];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_0[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_1[84];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_1[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_2[47];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_2[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_3[4];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_3[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_4[4];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_4[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_5[4];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_5[];
extern Vtx troll_test_dl_Main_NoCol_mesh_layer_1_vtx_0[16];
extern Gfx troll_test_dl_Main_NoCol_mesh_layer_1_tri_0[];
extern Gfx mat_troll_test_dl_Floor_001[];
extern Gfx mat_troll_test_dl_Wall_001[];
extern Gfx mat_troll_test_dl_Box_Platform_001[];
extern Gfx mat_revert_troll_test_dl_Box_Platform_001[];
extern Gfx mat_troll_test_dl_Interaction_001[];
extern Gfx mat_troll_test_dl_Interaction_002[];
extern Gfx mat_troll_test_dl_Death[];
extern Gfx troll_test_dl_Main_mesh_layer_1[];
extern Gfx troll_test_dl_Main_NoCol_mesh_layer_1[];
extern Gfx troll_test_dl_material_revert_render_settings[];
