extern const GeoLayout troll_test_area_1_geo[];
extern const GeoLayout troll_test_area_1[];
extern const Collision troll_test_area_1_collision[];
extern const MacroObject troll_test_area_1_macro_objs[];
extern Lights1 troll_test_dl_Floor_001_lights;
extern Lights1 troll_test_dl_Wall_001_lights;
extern u8 troll_test_dl_tex1_128x128_b07ede22d4ecf1c8_14_ci8[];
extern u8 troll_test_dl_tex1_128x128_b07ede22d4ecf1c8_14_ci8_pal_rgba16[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_0[8];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_0[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_1[46];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_1[];
extern Vtx troll_test_dl_Main_mesh_layer_1_vtx_2[26];
extern Gfx troll_test_dl_Main_mesh_layer_1_tri_2[];
extern Gfx mat_troll_test_dl_Floor_001[];
extern Gfx mat_troll_test_dl_Wall_001[];
extern Gfx mat_troll_test_dl_Box_Platform_001[];
extern Gfx mat_revert_troll_test_dl_Box_Platform_001[];
extern Gfx troll_test_dl_Main_mesh_layer_1[];
extern Gfx troll_test_dl_material_revert_render_settings[];
