extern const GeoLayout leaf_pile_geo[];
extern Lights1 leaf_pile_Leaves_lights;
extern u8 leaf_pile_Leaf_Pile_ci8[];
extern u8 leaf_pile_Leaf_Pile_ci8_pal_rgba16[];
extern Vtx leaf_pile_Circle_mesh_layer_1_vtx_0[24];
extern Gfx leaf_pile_Circle_mesh_layer_1_tri_0[];
extern Gfx mat_leaf_pile_Leaves[];
extern Gfx mat_revert_leaf_pile_Leaves[];
extern Gfx leaf_pile_Circle_mesh_layer_1[];
extern Gfx leaf_pile_material_revert_render_settings[];
